# Generated by Django 5.0.4 on 2024-04-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('description', models.TextField(max_length=120)),
                ('price', models.IntegerField()),
                ('pImage', models.ImageField(upload_to='images')),
            ],
        ),
    ]
