# Generated by Django 5.0.4 on 2024-04-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='cartItems',
            field=models.JSONField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
