# Generated by Django 5.0.4 on 2024-04-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_userdata_cartitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='cartItems',
            field=models.JSONField(default='{}'),
        ),
    ]
